Below: - Add a debug build in the releases - Use native file chooser dialogs instead of fyne' - Add information on README and website about debug build - Update go.mod and go.sum

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -78,13 +78,27 @@ jobs:
             --icon "dist/release/icon.png" \
             --ldflags="-s -w -X main.version=${{ env.GIT_TAG }}" \
             --name "${NAME}"
+          fyne-cross linux \
+            --arch ${arch} \
+            -env GOTOOLCHAIN=auto \
+            --icon "dist/release/icon.png" \
+            --ldflags="-X main.version=${{ env.GIT_TAG }}" \
+            --name "${NAME}-debug"
           echo "------------ fyne-cross worked hard. ------------"
           
           RAW_BINARY="./fyne-cross/bin/linux-${arch}/${NAME}"
+          RAW_DEBUG_BINARY="./fyne-cross/bin/linux-${arch}/${NAME}-debug"
 
           echo "Checking if binary exists before proceeding"
           if [ ! -f "${RAW_BINARY}" ]; then
             echo "Error: Binary for ${arch} not found at ${RAW_BINARY}"
+            exit 1
+          fi
+          echo "Done"
+
+          echo "Checking if debug binary exists before proceeding"
+          if [ ! -f "${RAW_DEBUG_BINARY}" ]; then
+            echo "Error: Binary for ${arch} not found at ${RAW_DEBUG_BINARY}"
             exit 1
           fi
           echo "Done"
@@ -94,9 +108,16 @@ jobs:
           rm -rf "${STAGING_DIR}"
           mkdir -p "${STAGING_DIR}"
           echo "Done"
+
+          echo "Setup Staging Area for debug build"
+          STAGING_DEBUG_DIR="./debug-staging"
+          rm -rf "${STAGING_DEBUG_DIR}"
+          mkdir -p "${STAGING_DEBUG_DIR}"
+          echo "Done"
           
           echo "Copy supporting files"
           cp "${RAW_BINARY}" "${STAGING_DIR}/"
+          cp "${RAW_DEBUG_BINARY}" "${STAGING_DEBUG_DIR}/"
           cp ./dist/release/install.sh "${STAGING_DIR}/" || true
           cp ./dist/release/update.sh "${STAGING_DIR}/" || true
           cp ./dist/release/uninstall.sh "${STAGING_DIR}/" || true
@@ -139,7 +160,9 @@ jobs:
           TAR_NAME="${NAME}-${arch}-${{ env.GIT_TAG }}.tar.xz"
           echo "Compressing to ${TAR_NAME}..."
           tar -cJf "./public/${TAR_NAME}" -C "${STAGING_DIR}" .
+          tar -cJf "./public/debug-build-${TAR_NAME}" -C "${STAGING_DEBUG_DIR}" .
           sha256sum "./public/${TAR_NAME}" > "./public/${TAR_NAME}.sha256"
+          sha256sum "./public/debug-build-${TAR_NAME}" > "./public/debug-build-${TAR_NAME}.sha256"
           echo "Done"
 
           # Cleanup for next iteration
